// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountcoowner"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountCoOwnerUpdate is the builder for updating AccountCoOwner entities.
type AccountCoOwnerUpdate struct {
	config
	hooks    []Hook
	mutation *AccountCoOwnerMutation
}

// Where appends a list predicates to the AccountCoOwnerUpdate builder.
func (_u *AccountCoOwnerUpdate) Where(ps ...predicate.AccountCoOwner) *AccountCoOwnerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountCoOwnerUpdate) SetAccountID(v int64) *AccountCoOwnerUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountCoOwnerUpdate) SetNillableAccountID(v *int64) *AccountCoOwnerUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *AccountCoOwnerUpdate) AddAccountID(v int64) *AccountCoOwnerUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AccountCoOwnerUpdate) SetUserID(v int64) *AccountCoOwnerUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AccountCoOwnerUpdate) SetNillableUserID(v *int64) *AccountCoOwnerUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AccountCoOwnerUpdate) AddUserID(v int64) *AccountCoOwnerUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AccountCoOwnerUpdate) SetCreatedBy(v int64) *AccountCoOwnerUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AccountCoOwnerUpdate) SetNillableCreatedBy(v *int64) *AccountCoOwnerUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *AccountCoOwnerUpdate) AddCreatedBy(v int64) *AccountCoOwnerUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *AccountCoOwnerUpdate) ClearCreatedBy() *AccountCoOwnerUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// Mutation returns the AccountCoOwnerMutation object of the builder.
func (_u *AccountCoOwnerUpdate) Mutation() *AccountCoOwnerMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountCoOwnerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountCoOwnerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountCoOwnerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountCoOwnerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AccountCoOwnerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(accountcoowner.Table, accountcoowner.Columns, sqlgraph.NewFieldSpec(accountcoowner.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(accountcoowner.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(accountcoowner.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(accountcoowner.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(accountcoowner.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(accountcoowner.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(accountcoowner.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(accountcoowner.FieldCreatedBy, field.TypeInt64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountcoowner.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountCoOwnerUpdateOne is the builder for updating a single AccountCoOwner entity.
type AccountCoOwnerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountCoOwnerMutation
}

// SetAccountID sets the "account_id" field.
func (_u *AccountCoOwnerUpdateOne) SetAccountID(v int64) *AccountCoOwnerUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountCoOwnerUpdateOne) SetNillableAccountID(v *int64) *AccountCoOwnerUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *AccountCoOwnerUpdateOne) AddAccountID(v int64) *AccountCoOwnerUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AccountCoOwnerUpdateOne) SetUserID(v int64) *AccountCoOwnerUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AccountCoOwnerUpdateOne) SetNillableUserID(v *int64) *AccountCoOwnerUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AccountCoOwnerUpdateOne) AddUserID(v int64) *AccountCoOwnerUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AccountCoOwnerUpdateOne) SetCreatedBy(v int64) *AccountCoOwnerUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AccountCoOwnerUpdateOne) SetNillableCreatedBy(v *int64) *AccountCoOwnerUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *AccountCoOwnerUpdateOne) AddCreatedBy(v int64) *AccountCoOwnerUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *AccountCoOwnerUpdateOne) ClearCreatedBy() *AccountCoOwnerUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// Mutation returns the AccountCoOwnerMutation object of the builder.
func (_u *AccountCoOwnerUpdateOne) Mutation() *AccountCoOwnerMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccountCoOwnerUpdate builder.
func (_u *AccountCoOwnerUpdateOne) Where(ps ...predicate.AccountCoOwner) *AccountCoOwnerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountCoOwnerUpdateOne) Select(field string, fields ...string) *AccountCoOwnerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountCoOwner entity.
func (_u *AccountCoOwnerUpdateOne) Save(ctx context.Context) (*AccountCoOwner, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountCoOwnerUpdateOne) SaveX(ctx context.Context) *AccountCoOwner {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountCoOwnerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountCoOwnerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AccountCoOwnerUpdateOne) sqlSave(ctx context.Context) (_node *AccountCoOwner, err error) {
	_spec := sqlgraph.NewUpdateSpec(accountcoowner.Table, accountcoowner.Columns, sqlgraph.NewFieldSpec(accountcoowner.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountCoOwner.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountcoowner.FieldID)
		for _, f := range fields {
			if !accountcoowner.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountcoowner.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(accountcoowner.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(accountcoowner.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(accountcoowner.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(accountcoowner.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(accountcoowner.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(accountcoowner.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(accountcoowner.FieldCreatedBy, field.TypeInt64)
	}
	_node = &AccountCoOwner{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountcoowner.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
