// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountcoowner"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountCoOwnerDelete is the builder for deleting a AccountCoOwner entity.
type AccountCoOwnerDelete struct {
	config
	hooks    []Hook
	mutation *AccountCoOwnerMutation
}

// Where appends a list predicates to the AccountCoOwnerDelete builder.
func (_d *AccountCoOwnerDelete) Where(ps ...predicate.AccountCoOwner) *AccountCoOwnerDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccountCoOwnerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountCoOwnerDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccountCoOwnerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accountcoowner.Table, sqlgraph.NewFieldSpec(accountcoowner.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccountCoOwnerDeleteOne is the builder for deleting a single AccountCoOwner entity.
type AccountCoOwnerDeleteOne struct {
	_d *AccountCoOwnerDelete
}

// Where appends a list predicates to the AccountCoOwnerDelete builder.
func (_d *AccountCoOwnerDeleteOne) Where(ps ...predicate.AccountCoOwner) *AccountCoOwnerDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccountCoOwnerDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accountcoowner.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountCoOwnerDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
