// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountcoowner"
)

// AccountCoOwnerCreate is the builder for creating a AccountCoOwner entity.
type AccountCoOwnerCreate struct {
	config
	mutation *AccountCoOwnerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAccountID sets the "account_id" field.
func (_c *AccountCoOwnerCreate) SetAccountID(v int64) *AccountCoOwnerCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AccountCoOwnerCreate) SetUserID(v int64) *AccountCoOwnerCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *AccountCoOwnerCreate) SetCreatedBy(v int64) *AccountCoOwnerCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *AccountCoOwnerCreate) SetNillableCreatedBy(v *int64) *AccountCoOwnerCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountCoOwnerCreate) SetCreatedAt(v time.Time) *AccountCoOwnerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountCoOwnerCreate) SetNillableCreatedAt(v *time.Time) *AccountCoOwnerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the AccountCoOwnerMutation object of the builder.
func (_c *AccountCoOwnerCreate) Mutation() *AccountCoOwnerMutation {
	return _c.mutation
}

// Save creates the AccountCoOwner in the database.
func (_c *AccountCoOwnerCreate) Save(ctx context.Context) (*AccountCoOwner, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountCoOwnerCreate) SaveX(ctx context.Context) *AccountCoOwner {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCoOwnerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCoOwnerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountCoOwnerCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountcoowner.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountCoOwnerCreate) check() error {
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountCoOwner.account_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AccountCoOwner.user_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountCoOwner.created_at"`)}
	}
	return nil
}

func (_c *AccountCoOwnerCreate) sqlSave(ctx context.Context) (*AccountCoOwner, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountCoOwnerCreate) createSpec() (*AccountCoOwner, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountCoOwner{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountcoowner.Table, sqlgraph.NewFieldSpec(accountcoowner.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(accountcoowner.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(accountcoowner.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(accountcoowner.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountcoowner.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountCoOwner.Create().
//		SetAccountID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountCoOwnerUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountCoOwnerCreate) OnConflict(opts ...sql.ConflictOption) *AccountCoOwnerUpsertOne {
	_c.conflict = opts
	return &AccountCoOwnerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountCoOwner.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountCoOwnerCreate) OnConflictColumns(columns ...string) *AccountCoOwnerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountCoOwnerUpsertOne{
		create: _c,
	}
}

type (
	// AccountCoOwnerUpsertOne is the builder for "upsert"-ing
	//  one AccountCoOwner node.
	AccountCoOwnerUpsertOne struct {
		create *AccountCoOwnerCreate
	}

	// AccountCoOwnerUpsert is the "OnConflict" setter.
	AccountCoOwnerUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountID sets the "account_id" field.
func (u *AccountCoOwnerUpsert) SetAccountID(v int64) *AccountCoOwnerUpsert {
	u.Set(accountcoowner.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountCoOwnerUpsert) UpdateAccountID() *AccountCoOwnerUpsert {
	u.SetExcluded(accountcoowner.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountCoOwnerUpsert) AddAccountID(v int64) *AccountCoOwnerUpsert {
	u.Add(accountcoowner.FieldAccountID, v)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AccountCoOwnerUpsert) SetUserID(v int64) *AccountCoOwnerUpsert {
	u.Set(accountcoowner.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountCoOwnerUpsert) UpdateUserID() *AccountCoOwnerUpsert {
	u.SetExcluded(accountcoowner.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *AccountCoOwnerUpsert) AddUserID(v int64) *AccountCoOwnerUpsert {
	u.Add(accountcoowner.FieldUserID, v)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *AccountCoOwnerUpsert) SetCreatedBy(v int64) *AccountCoOwnerUpsert {
	u.Set(accountcoowner.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *AccountCoOwnerUpsert) UpdateCreatedBy() *AccountCoOwnerUpsert {
	u.SetExcluded(accountcoowner.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *AccountCoOwnerUpsert) AddCreatedBy(v int64) *AccountCoOwnerUpsert {
	u.Add(accountcoowner.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *AccountCoOwnerUpsert) ClearCreatedBy() *AccountCoOwnerUpsert {
	u.SetNull(accountcoowner.FieldCreatedBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountCoOwner.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountCoOwnerUpsertOne) UpdateNewValues() *AccountCoOwnerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountcoowner.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountCoOwner.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountCoOwnerUpsertOne) Ignore() *AccountCoOwnerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountCoOwnerUpsertOne) DoNothing() *AccountCoOwnerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountCoOwnerCreate.OnConflict
// documentation for more info.
func (u *AccountCoOwnerUpsertOne) Update(set func(*AccountCoOwnerUpsert)) *AccountCoOwnerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountCoOwnerUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountCoOwnerUpsertOne) SetAccountID(v int64) *AccountCoOwnerUpsertOne {
	return u.Update(func(s *AccountCoOwnerUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountCoOwnerUpsertOne) AddAccountID(v int64) *AccountCoOwnerUpsertOne {
	return u.Update(func(s *AccountCoOwnerUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountCoOwnerUpsertOne) UpdateAccountID() *AccountCoOwnerUpsertOne {
	return u.Update(func(s *AccountCoOwnerUpsert) {
		s.UpdateAccountID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AccountCoOwnerUpsertOne) SetUserID(v int64) *AccountCoOwnerUpsertOne {
	return u.Update(func(s *AccountCoOwnerUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *AccountCoOwnerUpsertOne) AddUserID(v int64) *AccountCoOwnerUpsertOne {
	return u.Update(func(s *AccountCoOwnerUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountCoOwnerUpsertOne) UpdateUserID() *AccountCoOwnerUpsertOne {
	return u.Update(func(s *AccountCoOwnerUpsert) {
		s.UpdateUserID()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *AccountCoOwnerUpsertOne) SetCreatedBy(v int64) *AccountCoOwnerUpsertOne {
	return u.Update(func(s *AccountCoOwnerUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *AccountCoOwnerUpsertOne) AddCreatedBy(v int64) *AccountCoOwnerUpsertOne {
	return u.Update(func(s *AccountCoOwnerUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *AccountCoOwnerUpsertOne) UpdateCreatedBy() *AccountCoOwnerUpsertOne {
	return u.Update(func(s *AccountCoOwnerUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *AccountCoOwnerUpsertOne) ClearCreatedBy() *AccountCoOwnerUpsertOne {
	return u.Update(func(s *AccountCoOwnerUpsert) {
		s.ClearCreatedBy()
	})
}

// Exec executes the query.
func (u *AccountCoOwnerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountCoOwnerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountCoOwnerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountCoOwnerUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountCoOwnerUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountCoOwnerCreateBulk is the builder for creating many AccountCoOwner entities in bulk.
type AccountCoOwnerCreateBulk struct {
	config
	err      error
	builders []*AccountCoOwnerCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountCoOwner entities in the database.
func (_c *AccountCoOwnerCreateBulk) Save(ctx context.Context) ([]*AccountCoOwner, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountCoOwner, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountCoOwnerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountCoOwnerCreateBulk) SaveX(ctx context.Context) []*AccountCoOwner {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCoOwnerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCoOwnerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountCoOwner.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountCoOwnerUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountCoOwnerCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountCoOwnerUpsertBulk {
	_c.conflict = opts
	return &AccountCoOwnerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountCoOwner.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountCoOwnerCreateBulk) OnConflictColumns(columns ...string) *AccountCoOwnerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountCoOwnerUpsertBulk{
		create: _c,
	}
}

// AccountCoOwnerUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountCoOwner nodes.
type AccountCoOwnerUpsertBulk struct {
	create *AccountCoOwnerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountCoOwner.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountCoOwnerUpsertBulk) UpdateNewValues() *AccountCoOwnerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountcoowner.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountCoOwner.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountCoOwnerUpsertBulk) Ignore() *AccountCoOwnerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountCoOwnerUpsertBulk) DoNothing() *AccountCoOwnerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountCoOwnerCreateBulk.OnConflict
// documentation for more info.
func (u *AccountCoOwnerUpsertBulk) Update(set func(*AccountCoOwnerUpsert)) *AccountCoOwnerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountCoOwnerUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountCoOwnerUpsertBulk) SetAccountID(v int64) *AccountCoOwnerUpsertBulk {
	return u.Update(func(s *AccountCoOwnerUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountCoOwnerUpsertBulk) AddAccountID(v int64) *AccountCoOwnerUpsertBulk {
	return u.Update(func(s *AccountCoOwnerUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountCoOwnerUpsertBulk) UpdateAccountID() *AccountCoOwnerUpsertBulk {
	return u.Update(func(s *AccountCoOwnerUpsert) {
		s.UpdateAccountID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AccountCoOwnerUpsertBulk) SetUserID(v int64) *AccountCoOwnerUpsertBulk {
	return u.Update(func(s *AccountCoOwnerUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *AccountCoOwnerUpsertBulk) AddUserID(v int64) *AccountCoOwnerUpsertBulk {
	return u.Update(func(s *AccountCoOwnerUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountCoOwnerUpsertBulk) UpdateUserID() *AccountCoOwnerUpsertBulk {
	return u.Update(func(s *AccountCoOwnerUpsert) {
		s.UpdateUserID()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *AccountCoOwnerUpsertBulk) SetCreatedBy(v int64) *AccountCoOwnerUpsertBulk {
	return u.Update(func(s *AccountCoOwnerUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *AccountCoOwnerUpsertBulk) AddCreatedBy(v int64) *AccountCoOwnerUpsertBulk {
	return u.Update(func(s *AccountCoOwnerUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *AccountCoOwnerUpsertBulk) UpdateCreatedBy() *AccountCoOwnerUpsertBulk {
	return u.Update(func(s *AccountCoOwnerUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *AccountCoOwnerUpsertBulk) ClearCreatedBy() *AccountCoOwnerUpsertBulk {
	return u.Update(func(s *AccountCoOwnerUpsert) {
		s.ClearCreatedBy()
	})
}

// Exec executes the query.
func (u *AccountCoOwnerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountCoOwnerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountCoOwnerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountCoOwnerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
